version: "3.2"
services:
  consumer:
    depends_on:
      - rabbitmq
    build: consumer
    ports:
      - "5000:5000"
  wsreceiver:
    depends_on:
      - rabbitmq
    build: wsreceiver
    ports:
      - "8999:8999"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
#      - This gave me problems, commented out until I figure it out
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

